import type { Metadata } from "next";
import AppBar from "@/components/AppBar";
import { CssBaseline } from "@mui/material";
import Container from "@mui/material/Container";
import Box from "@mui/material/Box";

export const metadata: Metadata = {
  title: "Playlist Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <CssBaseline />
      <body>
      <AppBar />
      <Container maxWidth="lg">
        <Box sx={{ p: 4 }}>
          {children}
        </Box>
      </Container>
      </body>
    </html>
  );
}
