INSERT INTO SONG (id, title, artist, genre) VALUES (1, 'Bohemian Rhapsody', 'Queen', 'Rock');
INSERT INTO SONG (id, title, artist, genre) VALUES (2, 'Imagine', 'John Lennon', 'Pop');
INSERT INTO SONG (id, title, artist, genre) VALUES (3, 'Hotel California', 'Eagles', 'Rock');
INSERT INTO SONG (id, title, artist, genre) VALUES (4, 'Hey Jude', 'The Beatles', 'Pop');
INSERT INTO SONG (id, title, artist, genre) VALUES (5, 'Like a Rolling Stone', 'Bob Dylan', 'Folk Rock');
INSERT INTO SONG (id, title, artist, genre) VALUES (6, 'Smells Like Teen Spirit', 'Nirvana', 'Grunge');
INSERT INTO SONG (id, title, artist, genre) VALUES (7, 'Billie Jean', 'Michael Jackson', 'Pop');
INSERT INTO SONG (id, title, artist, genre) VALUES (8, 'What a Wonderful World', 'Louis Armstrong', 'Jazz');
INSERT INTO SONG (id, title, artist, genre) VALUES (9, 'Stairway to Heaven', 'Led Zeppelin', 'Rock');
INSERT INTO SONG (id, title, artist, genre) VALUES (10, 'Let It Be', 'The Beatles', 'Pop');